# Generated by Django 5.2.14 on 2026-08-12 02:59

import django.db.models.deletion
import tcc_portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=40)),
                ('turma', models.CharField(blank=True, default='Turma 01', max_length=80)),
                ('data_entrada', models.DateField()),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('concluida', 'Concluida'), ('arquivada', 'Arquivada')], default='ativa', max_length=20)),
                ('objetivo', models.TextField(blank=True, default='')),
                ('notas', models.TextField(blank=True, default='')),
                ('codigo', models.CharField(default=tcc_portal.models.gerar_codigo_acesso, max_length=20, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('fase_id', models.CharField(choices=[('onboarding', 'onboarding'), ('metodo', 'metodo'), ('narrativa', 'narrativa'), ('calendario', 'calendario'), ('roteiros', 'roteiros'), ('perfil', 'perfil'), ('prospeccao', 'prospeccao'), ('laboratorio', 'laboratorio')], max_length=32)),
                ('duracao', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(blank=True, default='')),
                ('capa_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('publicada', 'Publicada'), ('rascunho', 'Rascunho')], default='publicada', max_length=20)),
                ('destaque', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fase_id', models.CharField(choices=[('onboarding', 'onboarding'), ('metodo', 'metodo'), ('narrativa', 'narrativa'), ('calendario', 'calendario'), ('roteiros', 'roteiros'), ('perfil', 'perfil'), ('prospeccao', 'prospeccao'), ('laboratorio', 'laboratorio')], max_length=32)),
                ('texto', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aviso_mentora', models.TextField(blank=True, default='')),
                ('fase_atual_id', models.CharField(choices=[('onboarding', 'onboarding'), ('metodo', 'metodo'), ('narrativa', 'narrativa'), ('calendario', 'calendario'), ('roteiros', 'roteiros'), ('perfil', 'perfil'), ('prospeccao', 'prospeccao'), ('laboratorio', 'laboratorio')], default='onboarding', max_length=32)),
                ('mentora_nome', models.CharField(blank=True, default='', max_length=160)),
                ('abas_ocultas', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Configuracao',
                'verbose_name_plural': 'Configuracoes',
            },
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('fase_id', models.CharField(choices=[('onboarding', 'onboarding'), ('metodo', 'metodo'), ('narrativa', 'narrativa'), ('calendario', 'calendario'), ('roteiros', 'roteiros'), ('perfil', 'perfil'), ('prospeccao', 'prospeccao'), ('laboratorio', 'laboratorio')], max_length=32)),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('modelo', 'Modelo'), ('link', 'Link')], default='pdf', max_length=20)),
                ('url', models.URLField(blank=True, default='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('fase_id', models.CharField(choices=[('onboarding', 'onboarding'), ('metodo', 'metodo'), ('narrativa', 'narrativa'), ('calendario', 'calendario'), ('roteiros', 'roteiros'), ('perfil', 'perfil'), ('prospeccao', 'prospeccao'), ('laboratorio', 'laboratorio')], max_length=32)),
                ('prazo', models.DateField()),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baixa', 'Baixa')], default='media', max_length=20)),
            ],
            options={
                'ordering': ['prazo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField()),
                ('from_mentor', models.BooleanField(default=False)),
                ('aluna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_aula', to='tcc_portal.aluna')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tcc_portal.aula')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fase_id', models.CharField(blank=True, choices=[('onboarding', 'onboarding'), ('metodo', 'metodo'), ('narrativa', 'narrativa'), ('calendario', 'calendario'), ('roteiros', 'roteiros'), ('perfil', 'perfil'), ('prospeccao', 'prospeccao'), ('laboratorio', 'laboratorio')], default='', max_length=32)),
                ('texto', models.TextField()),
                ('aluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duvidas', to='tcc_portal.aluna')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fase_id', models.CharField(choices=[('onboarding', 'onboarding'), ('metodo', 'metodo'), ('narrativa', 'narrativa'), ('calendario', 'calendario'), ('roteiros', 'roteiros'), ('perfil', 'perfil'), ('prospeccao', 'prospeccao'), ('laboratorio', 'laboratorio')], max_length=32)),
                ('titulo', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, default='')),
                ('comentario', models.TextField(blank=True, default='')),
                ('aluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='tcc_portal.aluna')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fase_id', models.CharField(blank=True, choices=[('onboarding', 'onboarding'), ('metodo', 'metodo'), ('narrativa', 'narrativa'), ('calendario', 'calendario'), ('roteiros', 'roteiros'), ('perfil', 'perfil'), ('prospeccao', 'prospeccao'), ('laboratorio', 'laboratorio')], default='', max_length=32)),
                ('texto', models.TextField()),
                ('aluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='tcc_portal.aluna')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RespostaDuvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField()),
                ('from_mentor', models.BooleanField(default=False)),
                ('aluna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas_duvida', to='tcc_portal.aluna')),
                ('duvida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='tcc_portal.duvida')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistMarcado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_marcado', to='tcc_portal.aluna')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcacoes', to='tcc_portal.checklistitem')),
            ],
            options={
                'unique_together': {('aluna', 'item')},
            },
        ),
        migrations.CreateModel(
            name='DesafioStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topei', models.BooleanField(default=False)),
                ('feito', models.BooleanField(default=False)),
                ('aluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_status', to='tcc_portal.aluna')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_alunas', to='tcc_portal.desafio')),
            ],
            options={
                'unique_together': {('aluna', 'desafio')},
            },
        ),
        migrations.CreateModel(
            name='ProgressoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_aulas', to='tcc_portal.aluna')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to='tcc_portal.aula')),
            ],
            options={
                'unique_together': {('aluna', 'aula')},
            },
        ),
        migrations.CreateModel(
            name='TarefaConcluida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_concluidas', to='tcc_portal.aluna')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to='tcc_portal.tarefa')),
            ],
            options={
                'unique_together': {('aluna', 'tarefa')},
            },
        ),
    ]
