# Generated by Django 5.2.14 on 2026-09-05 03:14

import desafio.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dia', models.PositiveSmallIntegerField(unique=True)),
                ('titulo', models.CharField(max_length=160)),
                ('data_liberacao', models.DateField()),
            ],
            options={
                'ordering': ['dia'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=40)),
                ('instagram', models.CharField(blank=True, default='', max_length=80)),
                ('codigo_acesso', models.CharField(default=desafio.models.gerar_codigo_acesso, max_length=20, unique=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField()),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='desafio.participante')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comprovacao', models.TextField(blank=True, default='')),
                ('concluida_em', models.DateField()),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to='desafio.missao')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to='desafio.participante')),
            ],
            options={
                'ordering': ['-concluida_em'],
                'unique_together': {('participante', 'missao')},
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='desafio.participante')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('participante', 'data')},
            },
        ),
        migrations.CreateModel(
            name='PontoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('publicacao', 'Publicação na comunidade'), ('missao', 'Missão concluída'), ('prazo', 'Conclusão dentro do prazo'), ('comprovacao', 'Envio da comprovação'), ('streak', 'Sequência de dias'), ('comentario', 'Comentário em post de colega'), ('checkin', 'Check-in diário')], max_length=20)),
                ('pontos', models.IntegerField()),
                ('referencia', models.CharField(max_length=80)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='desafio.participante')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('participante', 'tipo', 'referencia')},
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField()),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='desafio.participante')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='desafio.post')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('post', 'participante')},
            },
        ),
    ]
