# Generated by Django 5.2.14 on 2026-09-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0002_participante_indicada_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoevento',
            name='tipo',
            field=models.CharField(choices=[('publicacao', 'Publicação na comunidade'), ('missao', 'Missão concluída'), ('prazo', 'Conclusão dentro do prazo'), ('comprovacao', 'Envio da comprovação'), ('streak', 'Sequência de dias'), ('comentario', 'Comentário em post de colega'), ('checkin', 'Check-in diário'), ('ajuste', 'Ajuste da organizadora')], max_length=20),
        ),
    ]
