# Generated by Django 5.2.12 on 2026-03-26 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=160)),
                ('contact', models.CharField(max_length=160)),
                ('stage', models.CharField(choices=[('Prospeccao', 'Prospeccao'), ('Negociacao', 'Negociacao')], max_length=30)),
                ('proposal_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('meeting_scheduled', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.workspace')),
            ],
            options={
                'ordering': ['stage', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=160)),
                ('project_name', models.CharField(max_length=180)),
                ('content_type', models.CharField(default='UGC Vertical', max_length=120)),
                ('stage', models.CharField(choices=[('Fechado', 'Fechado'), ('Entregue', 'Entregue')], default='Fechado', max_length=30)),
                ('status', models.CharField(choices=[('Briefing', 'Briefing'), ('Em gravacao', 'Em gravacao'), ('Em edicao', 'Em edicao'), ('Aguardando cliente', 'Aguardando cliente'), ('Aprovado', 'Aprovado'), ('Entregue', 'Entregue')], default='Briefing', max_length=40)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entry_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('received_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deliverables_count', models.PositiveIntegerField(default=1)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('close_date', models.DateField()),
                ('due_date', models.DateField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.workspace')),
            ],
            options={
                'ordering': ['stage', 'due_date', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='owner', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='studio.workspace')),
            ],
            options={
                'ordering': ['workspace__name', 'user__username'],
                'unique_together': {('user', 'workspace')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=255)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='studio.workspace')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('workspace', 'key')},
            },
        ),
    ]
