# Generated by Django 5.2.12 on 2026-03-27 03:02

import django.db.models.deletion
from django.db import migrations, models


def backfill_service_categories(apps, schema_editor):
    Project = apps.get_model("studio", "Project")
    ServiceCategory = apps.get_model("studio", "ServiceCategory")

    for project in Project.objects.exclude(project_name="").iterator():
        category, _ = ServiceCategory.objects.get_or_create(
            workspace_id=project.workspace_id,
            name=project.project_name,
        )
        if project.service_category_id != category.id or project.content_type:
            project.service_category_id = category.id
            project.content_type = ""
            project.save(update_fields=["service_category", "content_type"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_activeusersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='contact_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='prospect',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='prospect',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='prospect',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.workspace')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.AddField(
            model_name='prospect',
            name='niche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='studio.niche'),
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.workspace')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='studio.servicecategory'),
        ),
        migrations.RunPython(backfill_service_categories, noop_reverse),
    ]
