# Generated by Django 5.2.12 on 2026-03-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_prospect_contact_date_prospect_contact_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='avatar_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
