# Generated by Django 5.2.12 on 2026-03-27 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_membership_avatar_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closing_source',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='niche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='studio.niche'),
        ),
    ]
