# Generated by Django 5.2.12 on 2026-03-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_prospect_meeting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='avatar_data',
        ),
        migrations.AddField(
            model_name='membership',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='ugc_fotos/'),
        ),
    ]
