# Generated by Django 5.2.12 on 2026-04-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_remove_membership_avatar_data_membership_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meeting_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='business_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workspace',
            name='business_cnpj',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AddField(
            model_name='workspace',
            name='business_pis',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workspace',
            name='portfolio_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workspace',
            name='tiktok_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Briefing', 'Briefing'), ('Aguardando produto', 'Aguardando produto'), ('Em gravacao', 'Em gravacao'), ('Em edicao', 'Em edicao'), ('Aguardando cliente', 'Aguardando aprovacao'), ('Aprovado', 'Aprovado'), ('Entregue', 'Entregue')], default='Briefing', max_length=40),
        ),
    ]

