# Generated by Django 5.2.12 on 2026-04-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_project_meeting_date_project_meeting_scheduled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content_distribution',
            field=models.CharField(blank=True, choices=[('', 'Selecione'), ('Organico', 'Organico'), ('Ads', 'Ads')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='image_license_term_days',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(90, '90 dias'), (180, '180 dias'), (270, '270 dias'), (360, '360 dias')], null=True),
        ),
    ]
