# Generated by Django 5.2.12 on 2026-04-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_project_content_distribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='business_complement',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='workspace',
            name='business_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='business_street',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='workspace',
            name='business_zip_code',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
