# Generated by Django 5.2.12 on 2026-04-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_workspace_business_full_name_and_project_company_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content_distribution',
            field=models.CharField(blank=True, choices=[('', 'Selecione'), ('Organico', 'Orgânico'), ('Ads', 'Ads'), ('Nao se aplica', 'Não se aplica')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Briefing', 'Briefing'), ('Aguardando produto', 'Aguardando produto'), ('Em gravacao', 'Em gravação'), ('Em edicao', 'Em edição'), ('Aguardando cliente', 'Aguardando aprovação'), ('Aprovado', 'Aprovado'), ('Entregue', 'Entregue')], default='Briefing', max_length=40),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='stage',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Prospeccao', 'Prospecção'), ('Aguardando retorno', 'Aguardando retorno'), ('Negociacao', 'Negociação')], max_length=30),
        ),
    ]
