# Generated by Django 5.2.12 on 2026-04-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0015_alter_project_content_distribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='stage',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Prospeccao', 'Prospecção'), ('Aguardando retorno', 'Aguardando retorno'), ('Negociacao', 'Negociação'), ('Follow-up', 'Follow-up')], max_length=30),
        ),
    ]
