# Generated by Django 5.2.14 on 2026-05-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0021_add_fixed_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedcost',
            name='recurrence',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('annual', 'Anual')], default='monthly', max_length=20),
        ),
    ]
