# Generated by Django 5.2.14 on 2026-05-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0022_fixed_cost_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedcost',
            name='due_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=1),
        ),
    ]
