# Generated by Django 5.2.14 on 2026-06-01 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0024_cashbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_key', models.CharField(max_length=40)),
                ('product_name', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer_name', models.CharField(max_length=160)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_cpf', models.CharField(blank=True, default='', max_length=18)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=40)),
                ('mp_preference_id', models.CharField(blank=True, default='', max_length=80)),
                ('mp_payment_id', models.CharField(blank=True, default='', max_length=80)),
                ('payment_method', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('access_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='studio.accesscode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
