# Generated by Django 5.2.14 on 2026-06-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0029_financeentry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinstallment',
            name='label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
