# Generated by Django 5.2.14 on 2026-06-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0030_projectinstallment_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_beta',
            field=models.BooleanField(default=False),
        ),
    ]
