# Generated by Codex on 2026-06-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0031_workspace_is_beta"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("product_type", models.CharField(choices=[("mentorship", "Mentoria em grupo"), ("one_to_one", "Acompanhamento 1:1"), ("course", "Curso gravado"), ("template", "Planner / Template"), ("saas", "SaaS / Plataforma")], default="mentorship", max_length=30)),
                ("status", models.CharField(choices=[("active", "Ativo"), ("coming_soon", "Em breve"), ("paused", "Pausado"), ("closed", "Encerrado")], default="active", max_length=20)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("seats", models.PositiveIntegerField(blank=True, null=True)),
                ("platform", models.CharField(choices=[("Hubla", "Hubla"), ("Hotmart", "Hotmart"), ("Kiwify", "Kiwify"), ("Mercado Pago", "Mercado Pago"), ("Link Nubank", "Link Nubank"), ("Pix direto", "Pix direto")], default="Hubla", max_length=40)),
                ("sales_link", models.CharField(blank=True, default="", max_length=255)),
                ("access_duration", models.CharField(choices=[("unlimited", "Sem prazo"), ("1_month", "1 mês"), ("3_months", "3 meses"), ("6_months", "6 meses"), ("12_months", "12 meses")], default="unlimited", max_length=20)),
                ("track_progress", models.BooleanField(default=True)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="studio.workspace")),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("workspace", "name")},
            },
        ),
    ]
