# Generated by Django 5.2.14 on 2026-06-14 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0032_infoproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_name', models.CharField(max_length=180)),
                ('buyer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('platform', models.CharField(choices=[('Hubla', 'Hubla'), ('Hotmart', 'Hotmart'), ('Kiwify', 'Kiwify'), ('Mercado Pago', 'Mercado Pago'), ('Link Nubank', 'Link Nubank'), ('Pix direto', 'Pix direto')], default='Hubla', max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_date', models.DateField()),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('pendente', 'Pendente'), ('reembolsado', 'Reembolsado')], default='confirmado', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='studio.infoproduct')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.workspace')),
            ],
            options={
                'ordering': ['-sale_date', '-pk'],
            },
        ),
    ]
