# Generated by Django 5.2.14 on 2026-07-01 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0033_infoproductsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMonthlyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField()),
                ('status', models.CharField(choices=[('Briefing', 'Briefing'), ('Em produção', 'Em produção'), ('Aguardando aprovação', 'Aguardando aprovação'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Briefing', max_length=40)),
                ('note', models.CharField(blank=True, default='', max_length=180)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statuses', to='studio.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.workspace')),
            ],
            options={
                'ordering': ['month'],
                'unique_together': {('project', 'month')},
            },
        ),
    ]
