# Generated by Django 5.2.14 on 2026-07-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0034_project_monthly_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('layfe', 'layfeamorim.com'), ('tcc', 'The Creators Club'), ('dash', 'Dashcreator'), ('portfolio', 'Portfólio')], db_index=True, max_length=20)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('pageview', 'Pageview'), ('click', 'Clique')], default='pageview', max_length=12)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('visitor', models.CharField(blank=True, db_index=True, max_length=40)),
                ('session', models.CharField(blank=True, max_length=40)),
                ('referrer', models.CharField(blank=True, max_length=300)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', 'created_at'], name='studio_page_site_51c865_idx'), models.Index(fields=['site', 'kind', 'created_at'], name='studio_page_site_60cf36_idx')],
            },
        ),
    ]
