# Generated by Django 5.2.14 on 2026-07-06 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0036_project_image_rights_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='campaign_stage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='campaign_stage_dates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='roteiro_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='ProjectUpdateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_index', models.PositiveSmallIntegerField(default=0)),
                ('stage_label', models.CharField(blank=True, default='', max_length=80)),
                ('tone', models.CharField(default='neutro', max_length=20)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'Nova'), ('copied', 'Copiada'), ('ignored', 'Ignorada')], default='new', max_length=20)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_messages', to='studio.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
