# Generated by Django 5.2.14 on 2026-07-15 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0037_campaign_detail_assistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Briefing', 'Briefing'), ('Em produção', 'Em produção'), ('Aguardando aprovação', 'Aguardando aprovação'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Briefing', max_length=80),
        ),
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.workspace')),
            ],
            options={
                'ordering': ['position', 'name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='funnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='studio.funnel'),
        ),
        migrations.CreateModel(
            name='FunnelColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('position', models.PositiveIntegerField(default=0)),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='studio.funnel')),
            ],
            options={
                'ordering': ['position', 'name'],
                'unique_together': {('funnel', 'name')},
            },
        ),
    ]
