# Generated by Django 5.2.14 on 2026-07-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0040_project_contrato_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnelcolumn',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
