# Generated by Django 5.2.14 on 2026-07-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0044_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auto_key',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('workspace', 'auto_key')},
        ),
    ]
