# Generated by Django 5.2.14 on 2026-07-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0045_task_auto_key_alter_task_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
