# Generated by Django 5.2.14 on 2026-07-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0046_task_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_duration_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
