# Generated by Django 5.2.14 on 2026-07-19 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0047_task_category_task_estimated_duration_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('instagram', models.CharField(blank=True, default='', max_length=80)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.CharField(blank=True, default='', max_length=160)),
                ('stage', models.CharField(choices=[('prospec', 'Prospecção'), ('qualif', 'Qualificação'), ('proposta', 'Proposta Enviada'), ('negoc', 'Negociação'), ('fechado', 'Fechado'), ('perdido', 'Perdido')], db_index=True, default='prospec', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('origin', models.CharField(blank=True, default='', max_length=60)),
                ('next_action', models.CharField(blank=True, default='', max_length=160)),
                ('note', models.TextField(blank=True, default='')),
                ('loss_reason', models.CharField(blank=True, default='', max_length=160)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='studio.infoproduct')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.workspace')),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='InfoLeadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=240)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='studio.infolead')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='InfoLeadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='studio.infolead')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.workspace')),
            ],
            options={
                'ordering': ['done', 'due_date', 'pk'],
            },
        ),
    ]
