# Generated by Django 5.2.14 on 2026-07-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0048_infolead_crm'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delivered_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
