# Generated by Django 5.2.14 on 2026-08-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0050_backfill_delivered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='stage',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Prospeccao', 'Prospecção'), ('Follow-up', 'Follow-up'), ('Negociacao', 'Negociação'), ('Fechado', 'Fechado'), ('Sem Retorno', 'Sem Retorno')], max_length=30),
        ),
    ]
