# Generated by Django 5.2.14 on 2026-08-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0052_rename_aguardando_para_sem_retorno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infolead',
            name='stage',
            field=models.CharField(choices=[('prospec', 'Interessadas'), ('qualif', 'Qualificadas'), ('proposta', 'Negociação'), ('negoc', 'Recuperação'), ('fechado', 'Fechado'), ('perdido', 'Perdido')], db_index=True, default='prospec', max_length=20),
        ),
    ]
