# Generated by Django 5.2.14 on 2026-08-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0053_alter_infolead_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('product_key', models.CharField(max_length=40)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
