# Generated by Django 5.2.14 on 2026-09-06 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0054_coupon_purchase_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='brand_offer_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prospect',
            name='contact_outcome',
            field=models.CharField(blank=True, choices=[('', 'Aguardando resposta'), ('respondeu', 'Respondeu'), ('email', 'Direcionou para e-mail'), ('whatsapp', 'Direcionou para WhatsApp'), ('formulario', 'Enviou formulário'), ('agencia', 'Direcionou para agência'), ('responsavel', 'Falei com responsável'), ('recusou', 'Não faz parcerias agora')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='prospect',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prospect',
            name='negotiation_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prospect',
            name='proposal_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='recovery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='recovery_reason',
            field=models.CharField(blank=True, choices=[('nao_respondeu_contato', 'Não respondeu o primeiro contato'), ('nao_respondeu_proposta', 'Não respondeu a proposta'), ('sem_parcerias', 'Não está fazendo parcerias agora'), ('orcamento', 'Orçamento incompatível'), ('permuta', 'Ofereceu apenas permuta'), ('campanha_pausada', 'Campanha pausada'), ('sem_budget', 'Sem budget no momento'), ('nao_avancou', 'Oportunidade não avançou'), ('outro', 'Outro')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='prospect',
            name='stage_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='stage',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Primeiro Contato', 'Primeiro contato'), ('Qualificacao', 'Qualificação'), ('Proposta', 'Proposta enviada'), ('Follow-up', 'Follow-up'), ('Negociacao', 'Negociação'), ('Fechado', 'Fechado'), ('Recuperacao', 'Recuperação')], max_length=30),
        ),
        migrations.CreateModel(
            name='ProspectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('etapa', 'Mudança de etapa'), ('follow_up', 'Follow-up'), ('nota', 'Anotação')], default='nota', max_length=20)),
                ('text', models.CharField(max_length=240)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='studio.prospect')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
