# Generated by Django 5.2.14 on 2026-09-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0056_renomeia_etapas_prospeccao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infolead',
            name='stage',
            field=models.CharField(choices=[('prospec', 'Interessadas'), ('qualif', 'Qualificadas'), ('proposta', 'Proposta enviada'), ('negoc', 'Negociação'), ('fechado', 'Fechado'), ('perdido', 'Perdido')], db_index=True, default='prospec', max_length=20),
        ),
    ]
