# Generated by Django 5.2.14 on 2026-09-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0058_crm_interesse_e_conversao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventWaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=160)),
                ('whatsapp', models.CharField(max_length=40)),
                ('page', models.CharField(choices=[('imersivo', 'Imersivo'), ('editorial', 'Editorial'), ('site', 'Site')], default='site', max_length=20)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
