# Generated by Django 5.2.14 on 2026-09-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0059_lista_espera_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(db_index=True, max_length=40)),
                ('start', models.TimeField(verbose_name='início')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='fim')),
                ('title', models.CharField(max_length=160, verbose_name='atividade')),
                ('owner', models.CharField(blank=True, max_length=80, verbose_name='responsável')),
                ('details', models.TextField(blank=True, verbose_name='detalhes')),
            ],
            options={
                'verbose_name': 'horário do roteiro',
                'verbose_name_plural': 'roteiro do evento',
                'ordering': ['start', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EventSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(db_index=True, max_length=40)),
                ('category', models.CharField(choices=[('local', 'Espaço e estrutura'), ('comida', 'Comida e bebida'), ('decoracao', 'Decoração e ambientação'), ('foto', 'Foto e vídeo'), ('som', 'Som e luz'), ('skincare', 'Marcas de skincare'), ('kit', 'Kit e brindes'), ('grafica', 'Gráfica e sinalização'), ('equipe', 'Equipe de apoio'), ('transporte', 'Transporte'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='categoria')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('delivers', models.TextField(blank=True, verbose_name='o que entrega')),
                ('contact_name', models.CharField(blank=True, max_length=120, verbose_name='contato')),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=160, verbose_name='e-mail')),
                ('instagram', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('cotar', 'A cotar'), ('orcamento', 'Orçamento recebido'), ('negociando', 'Negociando'), ('fechado', 'Fechado'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='cotar', max_length=20, verbose_name='situação')),
                ('deal', models.CharField(choices=[('pago', 'Pago pelo clube'), ('permuta', 'Permuta'), ('patrocinio', 'Patrocínio (paga o clube)'), ('cortesia', 'Cortesia')], default='pago', max_length=20, verbose_name='acordo')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor combinado')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='já pago')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='vencimento')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'fornecedor do evento',
                'verbose_name_plural': 'fornecedores do evento',
                'ordering': ['category', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EventTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(db_index=True, max_length=40)),
                ('title', models.CharField(max_length=200, verbose_name='tarefa')),
                ('area', models.CharField(choices=[('local', 'Local e estrutura'), ('fornecedores', 'Fornecedores'), ('divulgacao', 'Divulgação'), ('vendas', 'Vendas e ingressos'), ('programacao', 'Programação'), ('kit', 'Kit e brindes'), ('dia', 'No dia'), ('pos', 'Pós-evento')], default='local', max_length=20, verbose_name='área')),
                ('owner', models.CharField(blank=True, max_length=80, verbose_name='responsável')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('done', models.BooleanField(default=False, verbose_name='feita')),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'tarefa do evento',
                'verbose_name_plural': 'tarefas do evento',
                'ordering': ['done', models.OrderBy(models.F('due_date'), nulls_last=True), 'pk'],
            },
        ),
    ]
