# Generated by Django 5.2.14 on 2026-09-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0060_gestao_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='business_city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='workspace',
            name='business_state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
