# Generated by Django 5.2.14 on 2026-10-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0061_cidade_do_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacesetting',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
