# Generated by Django 5.2.14 on 2026-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0062_settings_valor_longo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('kind', models.CharField(choices=[('convidada', 'Convidada'), ('equipe', 'Equipe'), ('marca', 'Marca parceira'), ('cortesia', 'Cortesia'), ('outro', 'Outro')], default='convidada', max_length=20, verbose_name='tipo')),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('pendente', 'Aguardando confirmar'), ('nao_vai', 'Não vai')], default='confirmada', max_length=20, verbose_name='situação')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=40)),
                ('instagram', models.CharField(blank=True, default='', max_length=80)),
                ('invited_by', models.CharField(blank=True, default='', max_length=80, verbose_name='convidada por')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'convidada do evento',
                'verbose_name_plural': 'convidadas do evento',
                'ordering': ['kind', 'name', 'pk'],
            },
        ),
    ]
