# Generated by Django 5.2.14 on 2026-10-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0064_centralfinanceentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20),
        ),
    ]
