from django.urls import path

from .checkout_views import (
    checkout_failure,
    checkout_page,
    checkout_payment,
    checkout_preference,
    checkout_status,
    checkout_success,
    checkout_webhook,
)
from .views import (
    AppLoginView,
    AppPasswordResetCompleteView,
    AppPasswordResetConfirmView,
    AppPasswordResetDoneView,
    AppPasswordResetView,
    business_cnpj_lookup,
    dashboard,
    distribution,
    planning,
    finance,
    installment_confirm,
    business_zip_lookup,
    legal_contract_dismiss,
    legal_contract_pdf,
    legal_contract_preview,
    legal_usage_dismiss,
    follow_up_confirm,
    follow_up_dismiss,
    follow_up_start_prospection,
    home,
    infoproducts,
    jobs,
    legal,
    profile,
    project_create,
    project_delete,
    project_detail,
    project_detail_advance,
    project_detail_save,
    project_edit,
    project_mark_delivered,
    project_message_action,
    project_set_status,
    funnel_create,
    funnel_column_create,
    funnel_column_update,
    funnel_column_delete,
    funnel_column_reorder,
    task_create,
    task_toggle,
    task_delete,
    task_schedule,
    prospection,
    prospect_archive,
    prospect_convert,
    prospect_create,
    prospect_delete,
    prospect_edit,
    prospect_export,
    prospect_reactivate,
    prospect_set_stage,
    reports,
    settings,
    signup,
)
from .metrics import metrics_dashboard, track


urlpatterns = [
    path("", home, name="home"),
    path("login/", AppLoginView.as_view(), name="login"),
    path("senha/esqueci/", AppPasswordResetView.as_view(), name="password_reset"),
    path("senha/esqueci/enviado/", AppPasswordResetDoneView.as_view(), name="password_reset_done"),
    path("senha/redefinir/<uidb64>/<token>/", AppPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("senha/redefinir/concluido/", AppPasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("signup/", signup, name="signup"),
    path("dashboard/", dashboard, name="dashboard"),
    path("planejamento/", planning, name="planning"),
    path("prospeccao/", prospection, name="prospection"),
    path("prospeccao/novo/", prospect_create, name="prospect_create"),
    path("prospeccao/follow-up/confirmar/", follow_up_confirm, name="follow_up_confirm"),
    path("prospeccao/follow-up/dispensar/", follow_up_dismiss, name="follow_up_dismiss"),
    path("prospeccao/follow-up/prospeccao/", follow_up_start_prospection, name="follow_up_start_prospection"),
    path("prospeccao/<int:pk>/editar/", prospect_edit, name="prospect_edit"),
    path("prospeccao/<int:pk>/excluir/", prospect_delete, name="prospect_delete"),
    path("prospeccao/<int:pk>/converter/", prospect_convert, name="prospect_convert"),
    path("prospeccao/<int:pk>/arquivar/", prospect_archive, name="prospect_archive"),
    path("prospeccao/<int:pk>/reativar/", prospect_reactivate, name="prospect_reactivate"),
    path("prospeccao/<int:pk>/etapa/", prospect_set_stage, name="prospect_set_stage"),
    path("prospeccao/banco-de-marcas/exportar/", prospect_export, name="prospect_export"),
    path("trabalhos/", jobs, name="jobs"),
    path("infoprodutos/", infoproducts, name="infoproducts"),
    path("trabalhos/novo/", project_create, name="project_create"),
    path("trabalhos/<int:pk>/editar/", project_edit, name="project_edit"),
    path("trabalhos/<int:pk>/excluir/", project_delete, name="project_delete"),
    path("trabalhos/<int:pk>/entregar/", project_mark_delivered, name="project_mark_delivered"),
    path("trabalhos/<int:pk>/status/", project_set_status, name="project_set_status"),
    path("trabalhos/funis/novo/", funnel_create, name="funnel_create"),
    path("trabalhos/funis/<int:funnel_id>/colunas/novo/", funnel_column_create, name="funnel_column_create"),
    path("trabalhos/funis/<int:funnel_id>/colunas/ordem/", funnel_column_reorder, name="funnel_column_reorder"),
    path("trabalhos/funis/colunas/<int:column_id>/", funnel_column_update, name="funnel_column_update"),
    path("trabalhos/funis/colunas/<int:column_id>/excluir/", funnel_column_delete, name="funnel_column_delete"),
    path("dashboard/tarefas/nova/", task_create, name="task_create"),
    path("dashboard/tarefas/<int:pk>/toggle/", task_toggle, name="task_toggle"),
    path("dashboard/tarefas/<int:pk>/excluir/", task_delete, name="task_delete"),
    path("dashboard/tarefas/<int:pk>/agendar/", task_schedule, name="task_schedule"),
    path("trabalhos/<int:pk>/detalhe/", project_detail, name="project_detail"),
    path("trabalhos/<int:pk>/detalhe/avancar/", project_detail_advance, name="project_detail_advance"),
    path("trabalhos/<int:pk>/detalhe/salvar/", project_detail_save, name="project_detail_save"),
    path("trabalhos/<int:pk>/detalhe/mensagem/<int:message_id>/", project_message_action, name="project_message_action"),
    path("financeiro/", finance, name="finance"),
    path("financeiro/parcela/<int:pk>/confirmar/", installment_confirm, name="installment_confirm"),
    path("distribuicao/", distribution, name="distribution"),
    path("juridico/", legal, name="legal"),
    path("juridico/<int:pk>/contrato/preview/", legal_contract_preview, name="legal_contract_preview"),
    path("juridico/<int:pk>/contrato/", legal_contract_pdf, name="legal_contract_pdf"),
    path("juridico/<int:pk>/dispensar-contrato/", legal_contract_dismiss, name="legal_contract_dismiss"),
    path("juridico/<int:pk>/ignorar-licenca/", legal_usage_dismiss, name="legal_usage_dismiss"),
    path("juridico/cnpj/", business_cnpj_lookup, name="business_cnpj_lookup"),
    path("relatorios/", reports, name="reports"),
    path("perfil/", profile, name="profile"),
    path("perfil/cep/", business_zip_lookup, name="business_zip_lookup"),
    path("configuracoes/", settings, name="settings"),
    path("checkout/api/preference/", checkout_preference, name="checkout_preference"),
    path("checkout/api/payment/", checkout_payment, name="checkout_payment"),
    path("checkout/api/status/", checkout_status, name="checkout_status"),
    path("checkout/api/webhook/", checkout_webhook, name="checkout_webhook"),
    path("checkout/obrigado/", checkout_success, name="checkout_success"),
    path("checkout/erro/", checkout_failure, name="checkout_failure"),
    path("checkout/<slug:product_key>/", checkout_page, name="checkout_page"),
    path("api/track/", track, name="track"),
    path("metricas/", metrics_dashboard, name="metrics_dashboard"),
]
