from django.urls import path

from .checkout_views import (
    checkout_failure,
    checkout_page,
    checkout_preference,
    checkout_success,
    checkout_webhook,
)
from .views import (
    AppLoginView,
    AppPasswordResetCompleteView,
    AppPasswordResetConfirmView,
    AppPasswordResetDoneView,
    AppPasswordResetView,
    business_cnpj_lookup,
    dashboard,
    distribution,
    finance,
    business_zip_lookup,
    legal_contract_dismiss,
    legal_contract_pdf,
    legal_contract_preview,
    follow_up_confirm,
    follow_up_dismiss,
    follow_up_start_prospection,
    home,
    jobs,
    legal,
    profile,
    project_create,
    project_delete,
    project_edit,
    project_mark_delivered,
    prospection,
    prospect_convert,
    prospect_create,
    prospect_delete,
    prospect_edit,
    reports,
    settings,
    signup,
)


urlpatterns = [
    path("", home, name="home"),
    path("login/", AppLoginView.as_view(), name="login"),
    path("senha/esqueci/", AppPasswordResetView.as_view(), name="password_reset"),
    path("senha/esqueci/enviado/", AppPasswordResetDoneView.as_view(), name="password_reset_done"),
    path("senha/redefinir/<uidb64>/<token>/", AppPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("senha/redefinir/concluido/", AppPasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("signup/", signup, name="signup"),
    path("dashboard/", dashboard, name="dashboard"),
    path("prospeccao/", prospection, name="prospection"),
    path("prospeccao/novo/", prospect_create, name="prospect_create"),
    path("prospeccao/follow-up/confirmar/", follow_up_confirm, name="follow_up_confirm"),
    path("prospeccao/follow-up/dispensar/", follow_up_dismiss, name="follow_up_dismiss"),
    path("prospeccao/follow-up/prospeccao/", follow_up_start_prospection, name="follow_up_start_prospection"),
    path("prospeccao/<int:pk>/editar/", prospect_edit, name="prospect_edit"),
    path("prospeccao/<int:pk>/excluir/", prospect_delete, name="prospect_delete"),
    path("prospeccao/<int:pk>/converter/", prospect_convert, name="prospect_convert"),
    path("trabalhos/", jobs, name="jobs"),
    path("trabalhos/novo/", project_create, name="project_create"),
    path("trabalhos/<int:pk>/editar/", project_edit, name="project_edit"),
    path("trabalhos/<int:pk>/excluir/", project_delete, name="project_delete"),
    path("trabalhos/<int:pk>/entregar/", project_mark_delivered, name="project_mark_delivered"),
    path("financeiro/", finance, name="finance"),
    path("distribuicao/", distribution, name="distribution"),
    path("juridico/", legal, name="legal"),
    path("juridico/<int:pk>/contrato/preview/", legal_contract_preview, name="legal_contract_preview"),
    path("juridico/<int:pk>/contrato/", legal_contract_pdf, name="legal_contract_pdf"),
    path("juridico/<int:pk>/dispensar-contrato/", legal_contract_dismiss, name="legal_contract_dismiss"),
    path("juridico/cnpj/", business_cnpj_lookup, name="business_cnpj_lookup"),
    path("relatorios/", reports, name="reports"),
    path("perfil/", profile, name="profile"),
    path("perfil/cep/", business_zip_lookup, name="business_zip_lookup"),
    path("configuracoes/", settings, name="settings"),
    path("checkout/<slug:product_key>/", checkout_page, name="checkout_page"),
    path("checkout/api/preference/", checkout_preference, name="checkout_preference"),
    path("checkout/api/webhook/", checkout_webhook, name="checkout_webhook"),
    path("checkout/obrigado/", checkout_success, name="checkout_success"),
    path("checkout/erro/", checkout_failure, name="checkout_failure"),
]
